apiVersion: v1
kind: ReplicationController
metadata:
  name: demo-rc
  labels:
    app: demo-app
    type: backend-app
spec:
  template:
    metadata:
      name: demo-pod
      labels:
        app: demo-app
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
          env:
            - name: FOO
              value: foo@value
            - name: BAR
              value: bar_value
  replicas: 4